spring:
  profiles:
    active: consumer #options: consumer | producer | consumer,producer | disabled

solace:
  jms:
    host: tcps://ems2.swim.faa.gov:55443
    msgVpn: TFMS
    clientUsername: xxxxxxxxxx
    clientPassword: xxxxxxxxxx
    connectionFactoryJndiName: xxxxxxxxxx
    producerQueueJndiName: xxxxxxxxxx
    consumerQueueJndiName: xxxxxxxxxx

logging:
  level:
    com:
      solacesystems: INFO


